### ISSUE TITLE
Submission plan

### ISSUE THREAD

**Issue by ijyliu** [ijyliu/ECMA-31330-Project#100]
@marionoro should probably be the one to do the upload since he submitted the earlier stuff and we definitely don't want to send them stuff from multiple people

- [x] Resolve remaining issues which are mostly theory related
- [x] Final approval/check for @ijyliu
- [x] Final approval/check for @marionoro
- [x] Final approval/check for @nicomarto  
- [x] Upload the paper
- [x] Upload the code. I think the most convenient thing would be to add the zipped version of the repo which you can do from the main page with the green button. If that doesn't work it's annoying but doable to submit the python files and notebooks I guess. Put in a note or comment to read the read me (it has a description of how the code was run) and also a link to this repo if possible

**Comment by marionoro** [comment]
Wouldn't it be better to just submit the Source folder, instead of submitting the entire repo?

**Comment by ijyliu** [comment]
if you submit the whole thing the readme is included. but probably doesn't matter

**Comment by marionoro** [comment]
How about I change the name of the folder from "Source" to "Commented Code" so that it's clear for them?

**Comment by ijyliu** [comment]
Yeah, but don't do it to the repo copy cause that will break things

**Comment by marionoro** [comment]
Okay

**Comment by ijyliu** [comment]
I guess we just kind of wait for nico now

**Comment by marionoro** [comment]
Are the terms used on Github standard? I've never heard of dividing folders into "Source", "Release", etc.

**Comment by marionoro** [comment]
Not a huge surprise, but the whole folder is taking a long time to upload to Canvas lol.

**Comment by ijyliu** [comment]
No but I wish more people used the same directory structure lol

**Comment by marionoro** [comment]
Alright, I submitted it as it currently is.

**Comment by marionoro** [comment]
Nico has 30 minutes left in his final and then he'll be able to work on this.

**Comment by marionoro** [comment]
Do we have non-parallelized code that does exactly what our submitted parallel code does? Maybe it would be helpful to email that to Nadav in case he can't run the parallelized code for some reason.

Also, I'm not sure how we can let them know that reading the readme explains everything, since you don't seem to be able to attach a note to your submission of files.

**Comment by ijyliu** [comment]
I think you can leave a comment on canvas

**Comment by ijyliu** [comment]
I mean technically there's like no way they can run the code since it would take too long. But I'll dig through and find the latest non-parallel version. Then can copy-paste into that to make sure it's up to date

**Comment by marionoro** [comment]
I do not see how to do so.

**Comment by ijyliu** [comment]
![image](https://user-images.githubusercontent.com/67396209/120907478-c96c1b80-c62f-11eb-9a4a-26f79226dab5.png)

you can definitely do it somehow. it might be after you submit

**Comment by ijyliu** [comment]
Click view feedback

**Comment by ijyliu** [comment]
So here's your old jupyternotebook. Should be able to copy paste and make minor edits inside the loop.

https://github.com/ijyliu/ECMA-31330-Project/blob/ab31254d835b80da44cded58a27e302b1c8f217e/Source/Simulations/Run_Simulations.ipynb

**Comment by marionoro** [comment]
Ah I see! I thought only the professor could leave a comment there.

**Comment by ijyliu** [comment]
@marionoro pdf now finalized

**Comment by ijyliu** [comment]
did the code thing work out ok

**Comment by marionoro** [comment]
Wait have you made changes since 8:41?

**Comment by ijyliu** [comment]
Yes but only to the pdf

**Comment by marionoro** [comment]
Alright, I'll submit again.

**Comment by ijyliu** [comment]
Sorry for any prior miscommunication here. You have the (hopefully satisfying) honor of checking the last two boxes and closing this issue tho.

**Comment by marionoro** [comment]
Thank you letting me have this honor lol.

Here we go. Thank y'all for working on this project together!

![image](https://user-images.githubusercontent.com/54335685/120910387-25d93600-c644-11eb-9a51-6221df82c3f0.png)
