### ISSUE TITLE
Literature Review

### ISSUE THREAD

**Issue by ijyliu** [ijyliu/ECMA-31330-Project#18]
Even if we don't have to include literature review I think it can't possibly hurt us to have looked around and gained knowledge as to whether we're on the right track in terms of what we're doing.

Here are a lot of links (checking these off as i make a first pass skimming and taking brief notes):

- [x] Prior reference from Prof. Bonhomme: https://warwick.ac.uk/fac/soc/economics/staff/knagasawa/PartialEffects.pdf
- [x] General discussion of factors as way to reduce ME: https://www-annualreviews-org.proxy.uchicago.edu/doi/pdf/10.1146%2Fannurev-economics-080315-015058
- [x] Simple explanations: https://advstats.psychstat.org/book/factor/index.php#factor-analysis and http://web.pdx.edu/~newsomj/semclass/ho_latent.pdf
- [x] Interesting take on ME models as factor models: https://www.sciencedirect.com/science/article/pii/0304407694016763
- [x] Concern about ME in the latent variables/factors themselves: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4787301/

Overall summary of findings:
So it actually kind of seems like we are doing something unique, but it's not clear that what we are doing is better than existing approaches to measurement error. Like averaging or instrumenting variables with each other.

**Comment by nicomarto** [comment]
I am happy with lit review and with what Paul wrote about the curse of dimensionality, so very good here
