### ISSUE TITLE
Why is IV doing so well now?

### ISSUE THREAD

**Issue by ijyliu** [ijyliu/ECMA-31330-Project#90]
It seems like IV is now beating everything else by a ton in the sims. This is true in both the non-transformed and the half-transformed case.

This seems to have happened after the run Paul uploaded yesterday. You can see where the tables changed here: https://github.com/ijyliu/ECMA-31330-Project/commit/27c837e75e953764bbe076aab79b7a74ed5703b0

So I think this is the result of including an intercept in the simulations and the IV first stage, or switching from 2SLS by hand to the statsmodels package.

**Comment by ijyliu** [comment]
Note for isaac to maybe note in like the conclusion:

Ideal empirical setting might be more p and more principal components

With more time, could try to use an optimizer to find precisely ideal conditions for the estimator

**Comment by ijyliu** [comment]
@marionoro added this to conlusion

![image](https://user-images.githubusercontent.com/67396209/120870336-a88bc380-c566-11eb-9e29-cf8c2e2a42f5.png)

probably can close

**Comment by marionoro** [comment]
Hmm I don't think that we should add that. I don't think we need/should mention the ways in which what we did was incomplete.

**Comment by ijyliu** [comment]
ok I want to hear @nicomarto 's opinion tho

**Comment by nicomarto** [comment]
Hmm, I would say that instead of that we could say "an interesting extension of this project could be an empirical case where p is large and n small"?

**Comment by marionoro** [comment]
I think that makes sense.

**Comment by nicomarto** [comment]
good!

**Comment by ijyliu** [comment]
![image](https://user-images.githubusercontent.com/67396209/120871702-66fd1780-c56a-11eb-8d07-e3f0077ae6ec.png)

**Comment by marionoro** [comment]
Looks good to me.
