### ISSUE TITLE
Add something on curse of dimensionality as a problem for iv and exponential transformations as a problem for averaging and all measurements to theory section

### ISSUE THREAD

**Issue by ijyliu** [ijyliu/ECMA-31330-Project#92]
this is mentioned in the intro but i don't think it was discussed

**Comment by ijyliu** [comment]
notes: can probably get something on curse of dimensionality/too many instruments from class or online. for exponential transformations, maybe a toy example? idk

**Comment by ijyliu** [comment]
doing the exponential just gives more variance to the Z's for covariates. but pca does a good job summarizing this variance?

**Comment by ijyliu** [comment]
PCA's optimality of approximation must be at work here, we are introducing nonlinearity with the transform but pca is still the best way to model it linearly, better than the average

**Comment by marionoro** [comment]
Tbh, I'm not sure if it's tractable to come up with theoretical reasons for why the exponential transformation makes taking the average perform worse. Isn't the simple reason for that trend that without any scaling taking the average will roughly approximate the true value (since it's averaging white noise errors away), but with the transformation the average will no longer be centered on the true value because the scales are so different?

**Comment by ijyliu** [comment]
I guess if it's e^z, in a mean 0 environemnt when you throw in exponentials you will be adding strictly postitive items. So yes?

But then if PCA rearranges weightings to explain more variance, won't it be even more wrong

**Comment by ijyliu** [comment]
No, wait we are rescaling. But I forget if that is before or after the transform

**Comment by ijyliu** [comment]
Transform is before rescaling.

**Comment by marionoro** [comment]
Yup we transform then rescale then PCA

**Comment by ijyliu** [comment]
So I guess then it's probably not something to do with the mean, but with the variance of the mismeasured items

**Comment by marionoro** [comment]
I figured it had something to do with this:

![image](https://user-images.githubusercontent.com/54335685/120877694-95d0b900-c57d-11eb-9010-aabe7510c9b8.png)

Taking the exponential of the distribution totally warps the distribution, even if you re-scaled it again later.

**Comment by ijyliu** [comment]
So half the covariates are drawn from distributions like x and half from z

**Comment by marionoro** [comment]
Exactly. Where 0 is the true factor I guess?

**Comment by marionoro** [comment]
![image](https://user-images.githubusercontent.com/54335685/120877903-a2a1dc80-c57e-11eb-8adb-2da34a171ad3.png)

Although x+z has a lower "MAE" and "MSE" than x+x, so I'm not sure I really get the mechanism by which this makes taking the average less effective.

**Comment by ijyliu** [comment]
In z you are more likely to draw a negative value right

**Comment by ijyliu** [comment]
Because it's mean not median centered

**Comment by marionoro** [comment]
Correct

**Comment by marionoro** [comment]
More likely to draw a negative but because the standard deviation of e**x is so large, the normalization crams more of the density of the distribution to be closer to 0 (with then a corresponding fatter tail to the right of the distribution than there is in a normal distribution).

**Comment by ijyliu** [comment]
Ugh still not clear to me it's off center when you do a few draws from z and a few from x and average across them

**Comment by marionoro** [comment]
What do you mean? If you add a centered distribution and an off-center one, the sum of those distributions will still be off center (although more centered than just the off-center distribution alone). Example:

![image](https://user-images.githubusercontent.com/54335685/120878114-f5c85f00-c57f-11eb-841d-f94e99591ac5.png)

**Comment by marionoro** [comment]
![image](https://user-images.githubusercontent.com/54335685/120878176-48a21680-c580-11eb-838a-c567914f61fe.png)

**Comment by ijyliu** [comment]
Yeah but what's the mean of x+z/2

**Comment by marionoro** [comment]
![image](https://user-images.githubusercontent.com/54335685/120878284-edbcef00-c580-11eb-9c12-4a3e1edbd7d3.png)

**Comment by marionoro** [comment]
Yeah lol I'm getting confused haha. If it's the median that matters, then it makes sense why the transformations decrease performance. I don't quite get why the median would matter though.

**Comment by marionoro** [comment]
Here are the deciles of each distribution:

![image](https://user-images.githubusercontent.com/54335685/120878310-2361d800-c581-11eb-9eef-6a7f0af27b44.png)

**Comment by marionoro** [comment]
![image](https://user-images.githubusercontent.com/54335685/120878450-1f828580-c582-11eb-84d8-8d21581280b9.png)

**Comment by ijyliu** [comment]
Notes: doubtful we will be able to develop this theoretically. So, we will try to provide just a little justification within the simulation section.

What we have on curse of dimensionality in the sim section is fine.

However, we should aim to add a sentence on why transforming the variables makes averaging perform poorly.

@nicomarto will give us his thoughts on this

**Comment by nicomarto** [comment]
ok so what I suspect is it has to do something with this: since PCA tries to max the variance of the linear combinations of X, then clearly things changes when we take exponetial. If all is linear, smaple average is basically the linear combination that maximises the variance when all lineas are scaling the same. But when we take exponentials,  exp(x+e) and exp(x+u) have different difference than x+e and x+u, so the "amount" of variance that we explain with those variables is different. Under PCA and sample average, x+u and x+e have basically the same weight in PCA and sample av when maximasing the variance, but the weights for exp(x+u) and exp(x+e) are way different

**Comment by ijyliu** [comment]
Average is equal weight for each measurement. PCA is not and would be more able to adjust weights to capture more variance. It's still tricky though because everything is rescaled so I guess idk why the weights need to be not equal

**Comment by nicomarto** [comment]
Yeah, the thing is that since all our missmeasured var are of the form x+e, so basically the best linear combination is very close to the average (in fact with p goes to infinity the average converge to the observation). Then the difference with PCA and av when we are no using exp(x+e) comes from the variance of the estimator, since I believe PCA would slightly change the weights to favor does where e is close to zero since they are closer to the true observation.

This does not happen when we take exp(x+e), since now clearly there are substantial  differences between the optimal linear combination and the average

**Comment by nicomarto** [comment]
btw waht paul wrote sounds amazing

**Comment by ijyliu** [comment]
hmm i guess pca does always have lower sd in the table

**Comment by nicomarto** [comment]
I suspected that when doing the theory thing, and the simulation seems to support it. Intuitively, what PCA should be making is trying to keep all the noise behind. Then, the estimation of the true variable throuhg PCA should be more efficient that when doing sample average, and so the PCA "transfers" less variance to the estimated coefficientes than the sample average

**Comment by ijyliu** [comment]
> We would expect PCR to outperform taking the average of all covariate measurements under this multiple-scale measurement framework as these transformations would warp the measurement error distributions around the true covariate in a way that a simple average would not be able to capture (whereas PCA would be better able to deal with this issue)

alright. so idk if we are better off putting this in the paper or modifying it or leaving things as is

**Comment by nicomarto** [comment]
what does @marionoro say

**Comment by ijyliu** [comment]
Here's a modification to consider
> We would expect PCR to outperform taking the average of all covariate measurements under this multiple-scale measurement framework as these transformations would warp the measurement error distributions around the true covariate in a way that a simple average would not be able to capture (whereas PCA would be capable of optimally adjusting relevant weightings)

**Comment by marionoro** [comment]
I don't really understand the discussion so I defer to y'all haha

**Comment by nicomarto** [comment]
It sounds nice to mee @ijyliu

**Comment by ijyliu** [comment]
> We would expect PCR to outperform taking the average of all covariate measurements under this multiple-scale measurement framework as these transformations would warp some of the measurement error distributions around the true covariate in a way that a simple average would not be able to capture (whereas PCA would be capable of optimally adjusting relevant weightings)

warp some of the distributions

**Comment by nicomarto** [comment]
wait I got lost lol

**Comment by marionoro** [comment]
Wait so are we done here lol?

**Comment by nicomarto** [comment]
idk lol

**Comment by ijyliu** [comment]
> We would expect PCR to outperform taking the average of all covariate measurements under this multiple-scale measurement framework as these transformations would warp some of the measurement error distributions around the true covariate in a way that a simple average would not be able to capture (whereas PCA would be capable of optimally adjusting relevant weightings)

include this?

**Comment by marionoro** [comment]
That sounds good to me!

**Comment by nicomarto** [comment]
same !

**Comment by ijyliu** [comment]
![image](https://user-images.githubusercontent.com/67396209/120909186-7e0e3900-c640-11eb-86ba-5acc36738e2f.png)

ok here's the full paragraph

if good go ahead and close

**Comment by marionoro** [comment]
Looks good to me.
