### ISSUE TITLE
Picking Simulations

### ISSUE THREAD

**Issue by ijyliu** [ijyliu/ECMA-31330-Project#93]
Here's what I suggest. Pick two tables to put in the main text:
1. Simulation that most matches our empirical application (we already have this run. It is probably one of the rho tables in the paper at the moment)
2. Simulation under which PCA performs best relative to other estimators (we have some options for this but I will try one last crack with N roughly equal to p. Specifically: me_cov = 0, p table, N roughly equal to p, exp. Exp will hurt the mean estimator, p and N will ensure curse of dimensionality hurts the IV estimator, me_cov doesn't really do much). I think the thing to use here is parallel_p_apes_N_100_exp.tex

I don't think the beta tables show much so maybe we should completely toss those out.

**Comment by marionoro** [comment]
I made some changes:

![image](https://user-images.githubusercontent.com/54335685/120864877-91db7180-c552-11eb-93c2-3b687d02c90c.png)

Yeah, I figured that 10 charts would be too many in the Appendix, so I didn't include the rho charts. I'm open to being persuaded otherwise though.

**Comment by ijyliu** [comment]
> Yeah, I figured that 10 charts would be too many in the Appendix, so I didn't include the rho charts. I'm open to being persuaded otherwise though.

Ok yeah the rho chart we have is pretty good.

**Comment by ijyliu** [comment]
Let me read over that new paragraph, in the mean time I guess you should proofread everything else

**Comment by ijyliu** [comment]
Alright, made some revisions. But overall I think this issue is closed. I feel pretty good about the sim section, just need to work on everything else now.
