### ISSUE TITLE
Comments on Application Section

### ISSUE THREAD

**Issue by marionoro** [ijyliu/ECMA-31330-Project#95]
1. "(in order to enable interpretable principal component analysis)"
- I don't think that "interpretable" is the right word here.

2. have we updated the application code to match the simulation code?

3. More explicitly add something saying that we don't know which method is best (but maybe IV seems like it'd be best in this format because it was best in our simulation similar to this application?)

4."Fixed effects coefficients greatly reduce the magnitude of any potential causal effects and are insignificant."
- grammatically unclear

**Comment by ijyliu** [comment]
Ok 3 is up

**Comment by ijyliu** [comment]
4 has also been adjusted.

What do you suggest changing 1 to?

**Comment by marionoro** [comment]
Nice, good work. I think something like:

"in order to ensure that each measurement is equally weighted in the principal component analysis"

I don't think it is quite accurate to say that we are making those transformations to aid interpretability; we aren't reporting the principal component values at all, right?

**Comment by ijyliu** [comment]
"in order to ensure that each measurement is appropriately weighted", I don't think they would be "equally weghted"

**Comment by marionoro** [comment]
Yeah, I like that.

**Comment by ijyliu** [comment]
ok, i'll make that change. do you have anything more on 2

**Comment by marionoro** [comment]
Nope, I think all my comments have been resolved now.
