### ISSUE TITLE
Update Introduction

### ISSUE THREAD

**Issue by ijyliu** [ijyliu/ECMA-31330-Project#96]
It seems out of date

@marionoro ?

**Comment by ijyliu** [comment]
> One may then use this extracted value in a standard OLS regression (often referred to as PCR or Principal Components Regression), thus providing a way to identify the parameter of interest that does not require the assumptions of instrumental variable analysis. The method also allows for more complex and possibly more optimal weightings of mismeasurements relative to simple averaging, and is less vulnerable to the curse of dimensionality relative to the inclusion of many covariates.

Like this, seems like it could benefit from insights from sims

**Comment by ijyliu** [comment]
> In this paper, we present a theoretical framework and a Monte-Carlo analysis in order to show the properties and behavior of our estimator on large samples under standard assumptions.

may want to also mention the ideal conditions we look at in addition to standard assumptions

**Comment by ijyliu** [comment]
> Our estimator generally behaves as expected in this empirical setting, though it is unclear whether it performs any better or worse than the direct inclusion of covariates, their averaging, or the instrumentation of mismeasured variables with each other.

maybe no longer the most accurate description of the results?

**Comment by marionoro** [comment]
Just posted some changes. What do you think of it now?
