### ISSUE TITLE
End of theory section

### ISSUE THREAD

**Issue by ijyliu** [ijyliu/ECMA-31330-Project#97]
Is the first line supposed to be hk or hk' = (1/n etc)

![image](https://user-images.githubusercontent.com/67396209/120894788-4c698380-c5e8-11eb-8302-bcf14e536f0f.png)

Also, is it actually x_tilde or just x

@nicomarto

**Comment by nicomarto** [comment]
no, h_k, the linear combination of the "p" missmeasured observartions for the "k" covariate

**Comment by ijyliu** [comment]
so h_k is right

also is it or x_tilde

**Comment by nicomarto** [comment]
is it x_{i,k} bc is the 'i' observation of the 'k' covariate, so is like this:

"we could aproximate the true 'i' observation of any 'k' covariate by taking the linear combination of all the 'i' observations of the set of 'p' missmeasured varaibles

**Comment by ijyliu** [comment]
so this is good:

![image](https://user-images.githubusercontent.com/67396209/120907875-49e04b80-c633-11eb-9f80-543a927b0429.png)

**Comment by nicomarto** [comment]
oh wait wait, I understand. No, is \tilde. Is the true x only if n goes to infinity (since in that case all the errors go to zero)

**Comment by nicomarto** [comment]
and clearly I did something else wrong, is 1/p lol
