### ISSUE TITLE
would researcher know when adding more measurements to iv reduces preformance

### ISSUE THREAD

**Issue by ijyliu** [ijyliu/ECMA-31330-Project#98]
![image](https://user-images.githubusercontent.com/67396209/120895519-4a54f400-c5eb-11eb-8fc4-2a20ae36de28.png)

would they be able to tell that the variance gets messy? I mean they wouldn't actually be able to see the mape right

**Comment by ijyliu** [comment]
Maybe the language we have is fine since we are saying "if it would be expected"? @marionoro 

idk I guess there are tests for too many instruments, etc. out there

**Comment by marionoro** [comment]
Yeah I'm inclined to think that it would be fine because of the "it would be expected" wording. I agree though that I am not sure if the researcher would actually be able to foresee the point at which adding more instruments performs worse (although maybe there's a basic N/p formula for that).
